USE [DBQLBANHANG]
GO
/****** Object:  Table [dbo].[tblBill]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblBill](
	[IDBill] [int] IDENTITY(1,1) NOT NULL,
	[BillDate] [date] NULL,
	[IDStaff] [int] NULL,
	[TotalPay] [float] NULL,
	[UserID] [int] NULL,
	[codeCus] [char](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDBill] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblCustumer]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblCustumer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[codeCus] [char](10) NOT NULL,
	[nameCus] [nvarchar](150) NULL,
	[addressCus] [nvarchar](150) NULL,
	[phoneCus] [char](11) NULL,
	[emailCus] [nvarchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[codeCus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblDetailBill]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblDetailBill](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDBill] [int] NOT NULL,
	[CodeProduct] [char](20) NOT NULL,
	[QuantityProduct] [int] NULL,
	[PriceProductBuying] [float] NULL,
	[TotalMoney] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDBill] ASC,
	[CodeProduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblProduct]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblProduct](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[codeProduct] [char](20) NOT NULL,
	[nameProduct] [nvarchar](max) NULL,
	[descriptionProduct] [nvarchar](max) NULL,
	[idSup] [int] NULL,
	[quantityProductInput] [int] NULL,
	[priceProductInput] [float] NULL,
	[priceProductDown] [float] NULL,
	[colorPro] [varchar](50) NULL,
	[sizePro] [varchar](10) NULL,
	[material] [nvarchar](50) NULL,
	[genderUse] [nvarchar](5) NULL,
	[IDStyle] [int] NULL,
	[imageProduct1] [nvarchar](max) NULL,
	[imageProduct2] [nvarchar](max) NULL,
	[imageProduct3] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[codeProduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblStaff]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblStaff](
	[IDStaff] [int] IDENTITY(1,1) NOT NULL,
	[StaffName] [nvarchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDStaff] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblStyle]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblStyle](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[nameStyle] [nvarchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblSupplierProduct]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblSupplierProduct](
	[idSup] [int] IDENTITY(1,1) NOT NULL,
	[supplierName] [nvarchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[idSup] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblUser]    Script Date: 11/18/2023 5:14:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblUser](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[userName] [nvarchar](100) NULL,
	[userPass] [nvarchar](max) NULL,
	[userRole] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[tblBill] ON 

INSERT [dbo].[tblBill] ([IDBill], [BillDate], [IDStaff], [TotalPay], [UserID], [codeCus]) VALUES (1, CAST(N'2023-11-13' AS Date), NULL, NULL, NULL, N'0934103640')
INSERT [dbo].[tblBill] ([IDBill], [BillDate], [IDStaff], [TotalPay], [UserID], [codeCus]) VALUES (2, CAST(N'2023-11-13' AS Date), NULL, NULL, NULL, N'          ')
INSERT [dbo].[tblBill] ([IDBill], [BillDate], [IDStaff], [TotalPay], [UserID], [codeCus]) VALUES (3, CAST(N'2023-11-13' AS Date), NULL, NULL, NULL, N'666666666 ')
INSERT [dbo].[tblBill] ([IDBill], [BillDate], [IDStaff], [TotalPay], [UserID], [codeCus]) VALUES (1002, CAST(N'2023-11-17' AS Date), NULL, NULL, NULL, N'000222    ')
SET IDENTITY_INSERT [dbo].[tblBill] OFF
GO
SET IDENTITY_INSERT [dbo].[tblCustumer] ON 

INSERT [dbo].[tblCustumer] ([ID], [codeCus], [nameCus], [addressCus], [phoneCus], [emailCus]) VALUES (2, N'          ', N'', N'', N'           ', N'')
INSERT [dbo].[tblCustumer] ([ID], [codeCus], [nameCus], [addressCus], [phoneCus], [emailCus]) VALUES (1002, N'000222    ', N'Huyen', N'243/32/32Hoàng Diệup4q4', N'111445544  ', N'lammyhuyen140704@gmail.com')
INSERT [dbo].[tblCustumer] ([ID], [codeCus], [nameCus], [addressCus], [phoneCus], [emailCus]) VALUES (1, N'0934103640', N'Huyen', N'243/32/32 Hoàng Diệu p4,q4,TPHCM', N'0344695406 ', N'lammyhuyen140704@gmail.com')
INSERT [dbo].[tblCustumer] ([ID], [codeCus], [nameCus], [addressCus], [phoneCus], [emailCus]) VALUES (3, N'666666666 ', N'tyyyyyyyyyyyyyyyy', N'5555555556', N'64444444443', N'khoa@gmail.com')
SET IDENTITY_INSERT [dbo].[tblCustumer] OFF
GO
SET IDENTITY_INSERT [dbo].[tblDetailBill] ON 

INSERT [dbo].[tblDetailBill] ([ID], [IDBill], [CodeProduct], [QuantityProduct], [PriceProductBuying], [TotalMoney]) VALUES (1, 1, N'BCBE1               ', 2, 59000, NULL)
INSERT [dbo].[tblDetailBill] ([ID], [IDBill], [CodeProduct], [QuantityProduct], [PriceProductBuying], [TotalMoney]) VALUES (2, 2, N'BCBE1               ', 1, 59000, NULL)
INSERT [dbo].[tblDetailBill] ([ID], [IDBill], [CodeProduct], [QuantityProduct], [PriceProductBuying], [TotalMoney]) VALUES (3, 3, N'FCSCPC21            ', 1000, 222000, NULL)
INSERT [dbo].[tblDetailBill] ([ID], [IDBill], [CodeProduct], [QuantityProduct], [PriceProductBuying], [TotalMoney]) VALUES (1002, 1002, N'BCBE5               ', 2, 129000, NULL)
INSERT [dbo].[tblDetailBill] ([ID], [IDBill], [CodeProduct], [QuantityProduct], [PriceProductBuying], [TotalMoney]) VALUES (1003, 1002, N'FCSCPC13            ', 1, 79000, NULL)
INSERT [dbo].[tblDetailBill] ([ID], [IDBill], [CodeProduct], [QuantityProduct], [PriceProductBuying], [TotalMoney]) VALUES (1004, 1002, N'FCSCPC34            ', 1, 146000, NULL)
SET IDENTITY_INSERT [dbo].[tblDetailBill] OFF
GO
SET IDENTITY_INSERT [dbo].[tblProduct] ON 

INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'BCBE1               ', N'Tinh Chất Dưỡng Thể Body Chống Nắng & Dưỡng Sáng Da Toàn Thân Vaseline Healthy Bright 300ml', NULL, 1, NULL, 59000, 184000, NULL, NULL, NULL, NULL, 1, N'https://product.hstatic.net/1000006063/product/unilever_e_440c9ba7669d460ba38b8342a200baf1_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'BCBE2               ', N'Sữa Dưỡng Thể Body Dưỡng Trắng Da, Dưỡng Ẩm Toàn Thân Vaseline Healthy White', NULL, 1, NULL, 83000, 158000, NULL, NULL, NULL, NULL, 1, N'https://product.hstatic.net/1000006063/product/170_70bf682af7ae46ba988edccd930f3614_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'BCBE3               ', N'Kem Tắm Trắng Dành Cho Mặt Và Cơ Thể G9Skin White In Creamy Pack 200ml', NULL, 1, NULL, 159000, NULL, NULL, NULL, NULL, NULL, 1, N'https://product.hstatic.net/1000006063/product/3_bbba8c94cc62484fa72c2ad08bde0b51_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'BCBE4               ', N'Sữa Dưỡng Thể Chống Nắng Dưỡng Trắng Da Hatomugi UV Care & Moisturizing The UV Milky Gel SPF 31/PA+++ 250ml', NULL, 1, NULL, 110000, NULL, NULL, NULL, NULL, NULL, 1, N'https://product.hstatic.net/1000006063/product/3_3367ffbd130b46d688492da6d1b192b6_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'BCBE5               ', N'Sữa Dưỡng Trắng, Nâng Tông Da Body Useemi Gluta Plus Whitening Body Solution', NULL, 1, NULL, 129000, 399000, NULL, NULL, NULL, NULL, 1, N'https://product.hstatic.net/1000006063/product/useemi_copy_2_8540acb99dac4bb0a8a994237273b8a5_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC10            ', N'[NHẬP KHẨU][222 Miếng] Bông Tẩy Trang Lameila Makeup Cotton 3 Lớp Dày Dặn Làm Sạch Da CXT002', NULL, 9, NULL, 29000, 56800, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/148_668e08d90dc44a5f927d35d851e6824a_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC11            ', N'Bông tẩy Trang 100% Cotton Thổ Nhĩ Kỳ Ipek Klasik Cotton Pads', NULL, 9, NULL, 20900, 55800, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/c4c6ef909255c_1024x1024__1__22d91db2d39d4642a9f0e94da3f6d0c4_1024x1024_cd77b0b18fc14d2baff8498938061094_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC12            ', N'Serum 9 Wishes Tinh Chất Dưỡng Ẩm, Cấp Nước, Căng Bóng Da 9 Wishes Hydra Glowing Deep Hydration Ampule Serum 25ml', NULL, 9, NULL, 211000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/4_b6ca5a988d5244a9b007eeea427ea96f_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC13            ', N'Serum L''Oreal Tinh Chất Cấp Ẩm, Cải Thiện Nếp Nhăn L''Oreal Revitalift 1.5% Hyaluronic Acid Serum', NULL, 9, NULL, 79000, 359000, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/8_538d15f6a64443518cac3637c2ced412_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC14            ', N'Serum Balance Active Formula Tinh Chất Dưỡng Trắng Da Trị Thâm Balance Active Formula Vitamin C Brightening Serum', NULL, 9, NULL, 126000, 229000, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/dd_269e52aaa47c40a0b7982caa6745b31e_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC15            ', N'Mặt Nạ Thạch 2in1 Mờ Thâm, Cải Thiện Nếp Nhăn Vùng Mắt G9Skin Self Aesthetic Collagen Hydrogel Eye Patchg', NULL, 9, NULL, 35000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/12_71d7437a61014998bf33a82ade85689f_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC16            ', N'Tinh Chất Dưỡng Mi, Làm Dài, Dày Mi Etude My Lash Serum 9g', NULL, 9, NULL, 89000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/etude-my-lash-serum_61762b0654444db0b27a369f612b6a65_1024x1024_75edfda7eace4041857866ced2413382_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC17            ', N'Tinh Chất Dưỡng Mắt Giảm Bọng Mắt, Mờ Quầng Thâm & Làm Đầy Rãnh Nhăn L''oreal Paris Revitalift Hyaluronic Acid Eye Serum 20ml', NULL, 9, NULL, 389000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/9_c6ae9721eed9475f9547fde1f041add9_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC18            ', N'Tẩy Tế Bào Chết Chiết Xuất Từ Thiên Nhiên Nhật Bản Rosette Gommage 120g', NULL, 9, NULL, 88000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/0000_03f324c94f2e4017baf11d230df8331e_1024x1024_382c34a8f18443f99a3becc958ce9ec9_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC19            ', N'Mặt Nạ Đất Sét Trà Xanh Giúp Làm Sạch, Thu Nhỏ Lỗ Chân Lông Some By Mi Super Matcha Pore Clean Clay Mask 100g', NULL, 9, NULL, 263000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/some_by_mi_super_matcha_pore_clean_clay_mask_100g_thumnail_a202c22a746849e993b868c2eb88c2ac_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC20            ', N'Mặt Nạ Đất Sét Thải Độc Da Chiết Xuất Rau Má Dearmay Skin Detox Mask Cica Mud', NULL, 9, NULL, 11000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/dearmay_skin_detox_mask_cica_mud_385daf703eaa4ca88e03f364e352ad64_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC21            ', N'Sữa Rửa Mặt Làm Sạch Sâu Cho Da Nhạy Cảm Eucerin pH5 Facial Cleanser Sensitive Skin', NULL, 9, NULL, 222000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/eucerin_e_548a5300c3a34843b6b3c10ed383b1df_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC22            ', N'Xịt Khoáng Cấp Nước Evoluderm Atomiseur Eau Pure Water', NULL, 9, NULL, 145000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/evoluderm_copy_11_07ed8d28de3b4cb1924eb54082b01e84_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC23            ', N'Nước Xịt Khoáng Cấp Ẩm Và Bảo Vệ Da Vichy Mineralizing Thermal Water', NULL, 9, NULL, 364000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/vichy_a35c21074d7c49e989ba7eb29b34dd2c_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'FCSCPC24            ', N'Sữa Dưỡng Ẩm Ban Đêm Dành Cho Da Khô Cerave Developed With Dermatologists Facial Moisturising Lotion PM 52ml', NULL, 9, NULL, 304000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/1_c92a65fbf5f74b07991d7cc6ec576eac_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'FCSCPC25            ', N'Sữa Dưỡng Ẩm Chiết Xuất 8 Loại Trà B.O.M Eight Tea Cleansing Lotion 120ml', NULL, 9, NULL, 314000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/1052_c1d8c5a5e208439cb0669a505ceebe13_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'FCSCPC26            ', N'Sữa Dưỡng Ẩm Cân Bằng Da Mịn Màng Chiết Xuất Hạt Ý Dĩ Naturie Hatomugi Skin Conditioning Milk 230ml', NULL, 9, NULL, 179000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/untitled-2_eaf17684415647e0889069465aba6d19_1024x1024_cda4ad73ca37446f8de202d043fc503b_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC27            ', N'Kem Dưỡng Ẩm, Làm Sáng Da Chiết Xuất Hạt Ý Dĩ Hatomugi Moisturizing & Conditioning The Milky Cream 300g', NULL, 9, NULL, 119000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/23_f3620d10d0b8403a9716d43cfead7eba_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC29            ', N'Kem Dưỡng Ẩm, Cấp Nước Neutrogena Hydro Boost Water Gel', NULL, 9, NULL, 271000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/dd_gel_b2879746c8d84a22856364fe9f6cbf1a_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'FCSCPC30            ', N'Nước Hoa Hồng Không Mùi Dưỡng Ẩm, Làm Dịu Da Klairs Supple Preparation Unscented Toner 180ml', NULL, 9, NULL, 266000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/fs_don_copy_12_cb29aaa7164c4a8986c952c2754eab02_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'FCSCPC31            ', N'Nước Hoa Hồng Cân Bằng, Dưỡng Ẩm Hatomugi Moisturizing & Conditioning The Lotion 500ml', NULL, 9, NULL, 109000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/5_b1e26caaf0ab444fb2448c0f75b0a8d5_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'FCSCPC32            ', N'Nước Hoa Hồng Chiết Xuất Diếp Cá, Tía Tô Chinoshio Natural Skin Lotion 500ml', NULL, 9, NULL, 82000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/anh-bia_b288a111b3034dd28c6b66ea639389d3_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC33            ', N'Kem Chống Nắng Kiểm Soát Dầu La Roche-Posay Anthelios Dry Touch Finish Mattifying Effect 50ml', NULL, 9, NULL, 399000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/1_081b19d27c7046cf9c777f0a2a1f750d_1024x1024_copy_039c326a469640089e62bbfa3d6c64dd_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC34            ', N'Kem Chống Nắng Dạng Tinh Chất Mỏng Nhẹ Senka Perfect UV Essence SPF 50+/PA +++ 50g', NULL, 9, NULL, 146000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/vn-11134207-7qukw-lgpzcikoe04yb9_2f8da6a939a74adc9c4738620dd37de0_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC35            ', N'Kem Chống Nắng Bí Đao Quang Phổ Rộng Dành Cho Da Dầu, Nhạy Cảm Cocoon Winter Melon Sunscreen 50ml', NULL, 9, NULL, 395000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/sp8708880527_fa89eb63b52149d08d70320b6fc41820_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'FCSCPC36            ', N'Bộ Dưỡng Dầu Gội Suôn Mượt & Kem Dưỡng Sáng Hồng Da Tay Và Móng HASI Smooth Shining Shampoo 450g + Hand Nail Cream #Soothing Bright 80g', NULL, 9, NULL, 69000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/16_d6ac66f0a9fb4540a187f1fa6860ce1d_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'FCSCPC37            ', N'[2 Items] Bộ Đôi Cho Da Dầu Curél Sebum Trouble Care (Gel Dưỡng Da Sebum Facial 120ml + Sữa Rửa Mặt Sebum Foaming Wash 90ml', NULL, 9, NULL, 525000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/26_7690cb18dfab4efdadf1a51633a0c759_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC38            ', N'[2 Items] Bộ Đôi Dịu Nhẹ Cấp Ẩm Cho Da Set Eucerin Anti-age Hyaluron-filler First Serum HA Moisture Booster 30ml + Dermatoclean Cleansing Gel 200ml', NULL, 9, NULL, 889000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/23_dd8988e5a852465bb0cdecb5d7365999_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC39            ', N'Serum Some By Mi Tinh Chất Retinol Chống Lão Hóa, Căng Bóng Da Some By Mi Retinol Intense Reactivating Serum 30ml', NULL, 9, NULL, 369000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/some_by_mi_retinol_intense_reactivating_serum_30ml_63047628840f4eb2a39d44136fcf541b_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC40            ', N'Combo Mặt Nạ (Dưỡng Trắng, Cấp Ẩm, Chống Lão Hóa, Giảm Mụn, Phục Hồi Da)', NULL, 9, NULL, 139000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/fs_don_9bef22d368c44eb89044697658b4bb11_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5,, N'FCSCPC41            ', N'Mặt Nạ Miếng Dưỡng Trắng Cấp Ẩm & Bổ Sung Collagen Ngăn Ngừa Lão Hóa Banobagi Stem Cell Vitamin, Super Collagen Mask 30ml', NULL, 9, NULL, 17000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/untitled-1_a4ac24290a4f498d8bab3c7a6ba98edd_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC42            ', N'Tẩy Tế Bào Chết Hóa Học Thu Nhỏ Lỗ Chân Lông, Trị Mụn Đầu Đen Và Mụn Ẩn Paula''s Choice Skin Perfecting 2% BHA Liquid Exfoliant', NULL, 9, NULL, 709000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/1_b144147225be4525bb7b57b5519df560_1024x1024_copy_7a70c4f10a934b3ea89f103f257dd4d2_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC43            ', N'[Mini 30g] Mặt Nạ Tẩy Da Chết Dạng Hạt Giảm Mụn Đầu Đen, Dưỡng Ẩm Chiết Xuất Xương Rồng Huxley Scrub Mask Sweet Therapy', NULL, 9, NULL, 69000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/1_1efba2e28c7c4b8fa8dec18ea1c18399_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC44            ', N'Nhíp Gắp Mụn Đầu Đen Vacosi T07', NULL, 9, NULL, 61000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/8809399378989_89bc301d37614934a42a21d4f5046f2a_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC45            ', N'Serum L''oreal Tinh Chất Mờ Thâm Nám Sau 2 Tuần L''oreal Glycolic-Bright Instant Glowing Serum 30ml', NULL, 9, NULL, 319000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/10_9719dd7860684fdbb2bb4e2e9fe996ef_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC46            ', N'Serum Klairs Tinh Chất Vitamin C Giúp Mờ Thâm Nám, Trắng Sáng Dành Cho Da Dễ Kích Ứng Klairs Freshly Juiced Vitamin Drop 35ml', NULL, 9, NULL, 296000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/1_4c3508c73dc14b4596ff0cda4bc856f0_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC47            ', N'Kem Dưỡng Trắng Da, Mờ Thâm Nám Chỉ Trong 7 Ngày Angel''s Liquid 7 Day Glutathione 700 V-Cream 50ml', NULL, 9, NULL, 399000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/3_0ae0a8bf22374978a079be3763498886_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC48            ', N'[50g] Kem Chống Nắng Giảm Dầu, Nâng Tone Da Sáng Hồng The Saem Pink Sun Cream SPF50+/PA++++', NULL, 9, NULL, 149000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/khung_the_saem_chuan_1776b4ed747c44d5bb47dc677609da67_1024x1024_3457e330fedd4703b3c3a55ac2497c12_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC49            ', N'[9 mùi] Mặt Nạ Tinh Chất Cấp Ẩm Chuyên Sâu Jkosmec Ultimate Hydrating Essence Mask', NULL, 9, NULL, 8000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/jkosmec_2_03c39c841f45428fb1a67436e9d8f2d5_1024x1024_0cdd09879dac442f8ebc06ffe06a6d7f_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC50            ', N'Mặt Nạ Trị Mụn, Kiểm Soát Dầu Chiết Xuất Tràm Trà Naruko Tea Tree Shine Control & Blemish Clear Mask 26ml', NULL, 9, NULL, 25000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/naruko_xanh_mask_0c0f022e3a5742ae8f8ec88872519cca_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC51            ', N'Kem Rạn Da Dưỡng Ẩm & Làm Mờ Vết Rạn Dành Cho Bà Bầu FIXDERMA Freggers Stretch Mark Cream 60g', NULL, 9, NULL, 355000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/erma_shadow_spf30___gel_75g_58830b68f8e54f53a1c48dc2a0a4b2c6_1024x1024_3bb5b0c088b043ea9de7843ad08b1009_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC52            ', N'Dầu Chăm Sóc Da Giúp Mờ Sẹo, Giảm Rạn Da, Làm Đều Màu Da Bio-Oil Skincare Oil', NULL, 9, NULL, 299000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/59fc45c629454e16f3eb9e_d38f0458eee04827b5be5971a4e50db7_1024x1024_copy_0c75cc1379214166a930e787fa9e740c_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC53            ', N'Dầu Dưỡng Giảm Rạn Da, Giúp Da Săn Chắc Eucerin Caring Oil 100% Natural Oils 125ml', NULL, 9, NULL, 529000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/46_45b2e04848844e78b33832bb85003eb6_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC6             ', N'Sữa Rửa Mặt Ngừa Mụn, Sáng Da Nhật Bản Hatomugi Acne Care & Facial Washing 130g', NULL, 9, NULL, 54000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/14_b57326b8dfe2483096fd75db8a964cb4_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC7             ', N'Sữa Rửa Mặt Dạng Gel Dịu Nhẹ Cosrx Low pH Good Morning Gel Cleanser', NULL, 9, NULL, 139000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/3_977830d2494047b28c42651d1dee9c95_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC8             ', N'Sữa Rửa Mặt Dịu Nhẹ, Dành Cho Da Nhạy Cảm Simple Kind To Skin Refreshing Facial Wash 150ml', NULL, 9, NULL, 119000, NULL, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/simple_anh_dai_dien_693d2899f2734e2a8e06d9bf7633a38f_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'FCSCPC9             ', N'Nước Tẩy Trang Làm Sạch Sâu 3 In 1 L''Oreal Micellar Water Deep Cleansing', NULL, 9, NULL, 69000, 159000, NULL, NULL, NULL, NULL, 5, N'https://product.hstatic.net/1000006063/product/8_6e67c810e20947d3970e26df67e50d28_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC54                ', N'Dầu Dưỡng Tóc Cao Cấp, Cải Thiện Tóc Hư Tổn Fino Premium Touch Hair Oil B 70ml', NULL, 12, NULL, 209000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/fino_5057f860d667408ba424b9649cdd2051_1024x1024_75c40875cc5246458ba96e3dffc36ecc_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC55                ', N'Nước Dưỡng Tóc Giảm Gãy Rụng Và Làm Mềm Tóc Tinh Dầu Bưởi The Cocoon Pomelo Hair Tonic 140ml', NULL, 12, NULL, 130000, 290000, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/hop_qua_lon_50_d3d2738ad7734b31a17936f8c62b312e_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC56                ', N'Dầu Dưỡng Tóc L''Oreal Elseve Extraordinary Oil Serum 100ml', NULL, 12, NULL, 195000, 190000, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/43_d11fd0c49c2148838c62753737333e17_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC57                ', N'[Black Pink''s Choice - Limited Edition] Thuốc Gội Nhuộm Tóc Dạng Bọt Miseen Scene Hello Bubble Trendy Color Limited Edition', NULL, 12, NULL, 149000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/khung_the_saem_chuan_1776b4ed747c44d5bb47dc677609da67_1024x1024_3457e330fedd4703b3c3a55ac2497c12_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC58                ', N'[325ml] Dầu Xả Giữ Màu Cho Tóc Nhuộm L''Oreal Elseve Color Protect 7 Weeks Conditioner', NULL, 12, NULL, 105000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/6_8e1ea962833643b2b0aee2208201ffac_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC59                ', N'[Mini 100ml] Dầu Gội Giữ Màu Tóc Nhuộm Love Beauty And Planet Blooming Colour Shampoo	45,000₫', NULL, 12, NULL, 49000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/vichy_mini_cc7d830b999f43a68c675c6e67e40406_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC60                ', N'Kem Ủ Tóc Cao Cấp, Phục Hồi Tóc Hư Tổn DOVE Keratin 180ml', NULL, 12, NULL, 109000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/18_35d57d3ac4544c1b86acdface7083305_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC61                ', N'Kem Ủ Tóc Bưởi Giảm Gãy Rụng Tóc Mềm Mượt Chắc Khỏe Cocoon Pomelo Hair Mask 200ml', NULL, 12, NULL, 215000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/sp8708879371_8dfd84695f5949f9ada9459a12f5b225_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC62                ', N'Kem Ủ Tóc Ngăn Ngừa Gãy Rụng TRESemmé Salon Rebond Salon-Quality Treatment Mask 180ml', NULL, 12, NULL, 155000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/unilever_e_c42f38e0446649a5b8b55a500600e3bf_1024x1024_c1777b06e76940448cb1cc2640074952_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC63                ', N'[310ml] Dầu Gội Tinh Chất Dầu Bưởi Giúp Giảm Gãy Rụng & Kích Thích Mọc Tóc Cocoon Pomelo Shampoo', NULL, 12, NULL, 245000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/sp8708874943_916447986e7f4b51b5f3a0cfbe64e72f_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC64                ', N'Dầu Xả Serum Giàu Dưỡng Chất Mise en Scène Perfect Serum Original Conditioner 530g', NULL, 12, NULL, 206000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/3_copy_4_3f89536f3cec49ea84fbe941f52cd736_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (2, N'HC65                ', N'Dầu Gội Phục Hồi Hư Tổn, Ngăn Rụng Tóc Tsubaki Premium Repair Shampoo 490ml', NULL, 12, NULL, 149000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/u1_f19affda25844d4c9ddde3af5250edb4_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK100             ', N'Son Tint Bóng, Siêu Lì Cho Đôi Môi Căng Mọng Romand Dewyful Water Tint', NULL, 16, NULL, 268000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/romand_dewyful_water_tint_5g_bb07635023cc4989b568916730c2338a_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK101             ', N'Son Dưỡng Môi Cấp Ẩm Cho Môi Senka Perfect Aqua Lip Balm', NULL, 16, NULL, 85000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/83_19371cea471549cab8a67bae7accf7a6_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK102             ', N'[VE-EASY] Son Dưỡng Dạng Thỏi Có Màu Thuần Chay Dưỡng Ẩm Mềm Môi Romand Glasting Melting Balm', NULL, 16, NULL, 209000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/1_e9d545c8f98c4795883da1f813b54d8b_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK103             ', N'Son Dưỡng Môi Dưỡng Ẩm Chuyên Sâu Nivea 24H Melt-in Moisture Lip Care', NULL, 16, NULL, 106000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/4187a03520da77bb5605_grande_412f79e86981465493ee3290cff8e478_1024x1024_eaebf5ff9410403ba9d47d138f3f516d_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK104             ', N'[Season 3] Son Tint Bóng Dạng Thạch, Bền Màu, Lâu Trôi Cho Đôi Môi Căng Mọng, Ẩm Mịn Merzy The Watery Dew Tint', NULL, 16, NULL, 269000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/fs_don_copy_6_b38e863f5e244106a3178ce04361473d_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK105             ', N'[Màu 1-8] Son Tint Nước Siêu Lì, Lâu Trôi Romand Glasting Water Tint', NULL, 16, NULL, 158000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/tui_qua_28_1a2ce15f1d1f4f7eb8df9b7f69b5cc1f_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK106             ', N'Son Tint Bóng, Siêu Lì Cho Đôi Môi Căng Mọng Romand Dewyful Water Tint', NULL, 16, NULL, 268000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/romand_dewyful_water_tint_5g_bb07635023cc4989b568916730c2338a_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'MKEK107             ', N'Mặt Nạ Ngủ Môi Thuần Chay Cấp Ẩm, Trẻ Hóa Môi Glamrr Q Vegan B5 Super Lip Sleeping Mask', NULL, 16, NULL, 199000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/696_1885e14ec11643d0bb2c35d6fa79b10b_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (5, N'MKEK108             ', N' [3 mùi] Mặt Nạ Ngủ Môi Dưỡng Ẩm, Loại Bỏ Da Chết Cho Môi Hồng Hào Căng Mọng Hàn Quốc Carenel Lip Night Mask', NULL, 16, NULL, 99000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/3_copy_4_b039f766a8474f8bad06de3346682745_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK110             ', N'Tẩy Tế Bào Chết Môi Chiết Xuất Cà Phê Đắk Lắk Cocoon Dak Lak Coffee Lip Scrub', NULL, 16, NULL, 99000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/9800e8727b40a5d80_1024x1024_5dfe8a5ad56145fcabd5c5aa1c7bda5f_1024x1024_678dc633786e47c48040d21a2b8365dd_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK111             ', N'Son Thỏi Lì, Lên Màu Chuẩn I''m Meme Drawing Atelier Velvet Lipstick', NULL, 16, NULL, 189000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/i_m_meme_copy_701e2debe1194b0eb1328a6d0f0da50a_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK112             ', N'[Màu 1-8] Son Thỏi Lì Chất Siêu Mịn, Vỏ Vàng Cao Cấp G9Skin First V-Fit Lipstick', NULL, 16, NULL, 129000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/2_a6a32f2d867849418ea12f3e8db42572_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK118             ', N'Chì Kẻ Viền Môi Nhung Lì, Lâu Trôi, Thiết Kế 2 Đầu Romand Lip Mate Pencil', NULL, 16, NULL, 189000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/romand_c41217badc824c8fbccb1d5d78a292c8_1024x1024_copy_8eff3599392d4a69bd57be4101090c62_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK66              ', N'Bảng Phấn Mắt 16 Ô Siêu Mềm Mịn, Bền Màu, Lâu Trôi Lemonade Aesthetic Eyeshadow Palette 20.8g', NULL, 16, NULL, 339000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/1_db5d2e8ffb0a49328497563256caae94_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK67              ', N'Bảng Phấn Mắt 4 Ô Màu Siêu Xinh Romand Better Than Eyes', NULL, 16, NULL, 219000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/romand_better_than_eyes_k_co_tp_a23c26fe4d9943c3ad29f5171b1d4fba_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK68              ', N'Bảng Phấn Mắt 16 Ô Siêu Mịn, Bền Màu Zeesea Fireworks 16 Colors Eye Shadow', NULL, 16, NULL, 249000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/zeesea_copy_3_a8c1d70c65744a82a46d653279621288_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK69              ', N'Chì Kẻ Mày Hai Đầu Tiện Lợi Cho Lông Mày Hoàn Hảo Lemonade Want It Got It Dual Eyebrow', NULL, 16, NULL, 159000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/16_9fd2a134723548408e40ce0ce3c9a6ad_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK70              ', N'Chì Kẻ Chân Mày Siêu Mảnh Lilybyred Skinny Mes Brow Pencil', NULL, 16, NULL, 99000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/lilybyred_skinny_mes_brow_pencil_0.09g_1f824753113e4cc2bbdafcef95c9ba77_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK71              ', N'Chì Kẻ Mày Lâu Trôi, Dễ Kẻ, Lên Màu Chuẩn Maybelline Tattoo Brow Up To 36H Pigment Pencil', NULL, 16, NULL, 142000, NULL, NULL, NULL, NULL, NULL, 2, N'https://product.hstatic.net/1000006063/product/130_a7fa8aa9955840ecbbd3fba6b503cc41_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK72              ', N'Chì Kẻ Mắt Dạng Sáp Nét Mảnh, Lâu Trôi Romand Han All Shade Liner', NULL, 16, NULL, 308000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/202_d18ccebe6622478ba740919885401fb7_1024x1024_34053385b68547cfb0de3b33fad5f403_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK73              ', N'Bút Kẻ Mắt Nước Chống Trôi Merzy The First Pen Eyeliner', NULL, 16, NULL, 209000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/tui_qua_4_cc3486e280d44f25a0bd1eb6ca612278_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK74              ', N'Bút Kẻ Mắt Nước Siêu Mảnh, Chống Thấm Nước, Lâu Trôi Zeesea Black Lasting Eyeliner', NULL, 16, NULL, 108000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/tui_qua_9_fb00d50af68342f794105e29bf3bd0d7_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK75              ', N'[500 Miếng] Miếng Dán Mí Vacosi Eyelid Tape - Size S - VM11', NULL, 16, NULL, 63000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/3_copy_2_59f3ec3fef4a465a8146a58e63349a77_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK76              ', N'[NHẬP KHẨU] Lông Mi Giả Mềm Mại Tự Nhiên, Không Gây Nặng Mí LMLTOP Eyelash', NULL, 16, NULL, 119000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/1_a82c4744b44f488abc4b0bce3d5d5c0e_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK77              ', N'Vacosi Dán Mí Lưới VM16 (120 Miếng)', NULL, 16, NULL, 62000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/8809399372390.jpg_0f303ae92b2f45da8fcbbf13e1961108_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK78              ', N'Kem Che Khuyết Điểm Mịn Lì Lâu Trôi Cathy Doll Cover Matte Concealer', NULL, 16, NULL, 95000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/99ae1433d205244372348d7eb36f6423_7fc3f82796344e688a48ab405ba0dc45_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK79              ', N'Kem Che Khuyết Điểm Có Chống Nắng Hàn Quốc The Saem Cover Perfection Tip Concealer SPF28/PA++', NULL, 16, NULL, 109000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/4443_bf7c84eabb0c47cb9afe97252b697344_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK80              ', N'Bút Che Khuyết Điểm Đa Năng Che Phủ Hoàn Hảo Maybelline Instant Age Rewind Eraser Multi-Use Concealer SPF 30', NULL, 16, NULL, 169000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/9_d46b35f2ddd64c4a974e6018786bd51c_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK81              ', N'Kem Nền Kiềm Dầu, Cho Lớp Nền Mịn Lì Tự Nhiên Maybelline Fit Me Matte Poreless Foundation', NULL, 16, NULL, 199000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/9_copy_8_adc67e46b9034cf897accd93c53fc6ab_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK82              ', N'Kem Nền Kiềm Dầu, Che Khuyết Điểm Hoàn Hảo, Lâu Trôi Zeesea Silky Lasting Foundation', NULL, 16, NULL, 119000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/zeesea_silky_lasting_foundation_076e82ae9b5a4497b89494c7fa5b2601_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK83              ', N'Kem Lót Trang Điểm Kiềm Dầu, Nâng Tông Tự Nhiên, Che Khuyết Điểm, Làm Mịn Da Zeesea Multi-Effect Makeup Primer', NULL, 16, NULL, 139000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/zeesea_80ada6d07a6c4022b8e58e66aa5219a0_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK84              ', N'Kem Nền Tươi Mướt, Chống Nắng Bảo Vệ Da Maybelline New York Fit Me Fresh Tint SPF50/PA+++', NULL, 16, NULL, 169000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/7_a8e0e0d91e0d4b5c8e925be50401e2f7_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK85              ', N'Thỏi Tạo Khối Và Highlight Đa Năng Silkygirl Photo Sharp Contour & Highlight', NULL, 16, NULL, 174000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/silkyugirl_6fa8da6ee7b9429a8a7f6c08a60e84b4_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK86              ', N'Phấn Tạo Khối Hai Màu Romand Better Than Shape', NULL, 16, NULL, 189000, NULL, NULL, NULL, NULL, NULL, 3, N' https://product.hstatic.net/1000006063/product/romand_better_than_shape_k_co_tp_ac603c42700c4be9ac7c895ba116d7d8_1024x1024.jpg', NULL, NULL)
GO
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK87              ', N'Bộ Sưu Tập Phiên Bản Giới Hạn Romand x Sanrio My Melody Kuromi', NULL, 16, NULL, 519000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/800x800_web_sua_lai_4649feb0ae6841a0a292c5eb8cf7597c_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK89              ', N'[SUNSHINE CHEEK] Phấn Má Hồng Siêu Xinh Peripera Pure Blushed Sunshine Cheek', NULL, 16, NULL, 129000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/20_4798636934ef4796adeab75536e5d824_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK90              ', N'[SUNSHINE CHEEK] Phấn Má Hồng Siêu Xinh Peripera Pure Blushed Sunshine Cheek', NULL, 16, NULL, 129000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/20_4798636934ef4796adeab75536e5d824_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK91              ', N'Má Hồng Dạng Kem Mềm Mịn, Chuẩn Màu Bbia Ready To Wear Downy Cheek', NULL, 16, NULL, 139000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/613_b85a6c1d5e3440c49d684e0f2302314d_1024x1024_copy_156e627166394363860702a5d73c8d37_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK92              ', N'Phấn Phủ Dạng Bột Kiềm Dầu, Hiệu Ứng Mờ Lì, Cho Lớp Nền Mịn Màng, Lâu Trôi Merzy Stay Blur Loose Powder', NULL, 16, NULL, 239000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/merzy_stay_blur_loose_powder_d58a9078fb6a4dd39db44e061a8151f5_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK93              ', N'Phấn Phủ Kiềm Dầu, Ngăn Thấm Mồ Hôi Zeesea Air Loose Powder', NULL, 16, NULL, 249000, 129000, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/zeesea_5_140a0586f698479caea6c894de01625e_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK94              ', N'Phấn Phủ Dạng Bột Kiềm Dầu Cho Da Mịn Màng Silkygirl No Sebum Mineral Powder', NULL, 16, NULL, 249000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/595_d566744504ec4d8d986e1cbdd3a2d258_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK95              ', N'Phấn Nước Che Phủ Hoàn Hảo, Mỏng Nhẹ Tự Nhiên Romand NU Zero Cushion SPF24/PA++', NULL, 16, NULL, 309000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/3_52eff96f2bcd496888177866ef140dbb_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK96              ', N'Phấn Nước Che Phủ Mỏng Mịn, Kiềm Dầu Hiệu Quả Glamrr Q Long Wear DD Cushion SPF50/PA+++', NULL, 16, NULL, 339000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/glamrr_q_1_993e412fb3f2491aab478a62ad97ad64_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK97              ', N'[VE-EASY] Phấn Nước Trang Điểm Che Phủ Tự Nhiên, Căng Bóng Thuần Chay Romand Bare Water Cushion SPF38/PA++++', NULL, 16, NULL, 364000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/2_10d4d2cf732743a4bdf7782220191473_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK98              ', N'[M13 VỎ ĐỎ RED EDITION] Son Kem Siêu Lì, Mịn Môi Merzy Noir In The Mellow Tint', NULL, 16, NULL, 429000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/tui_qua_35_ae80a74f46374f18ab9dd3b0ba2b17fa_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (3, N'MKEK99              ', N'[FOIF by MERZY] Son Tint Bóng Thuần Chay, Ẩm Mọng, Bền Màu FOIF Juicy Fit Tint', NULL, 16, NULL, 109000, NULL, NULL, NULL, NULL, NULL, 3, N'https://product.hstatic.net/1000006063/product/thumbnail_ba9915c005c54d788370a7a703c6cc0c_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (1, N'PB112               ', N'[2 Items] Bộ Đôi Sữa Dưỡng Thể & Xịt Thơm Toàn Thân Hương Nước Hoa Malissa Kiss Whitening Body Lotion & Perfume Mist - Wanderlust', NULL, 19, NULL, 251000, NULL, NULL, NULL, NULL, NULL, 4, N'https://product.hstatic.net/1000006063/product/2_1_8bfaec399a9c4192b2ca9cdbb17876e3_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'PB113               ', N'Xịt Thơm Toàn Thân Bodyholic Stay Nudie Hair & Body Mist', NULL, 19, NULL, 189000, NULL, NULL, NULL, NULL, NULL, 4, N'https://product.hstatic.net/1000006063/product/2_5d03d674a02b4e1db8283a93eaa6d33e_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'PB114               ', N'Xịt Thơm Toàn Thân Cho Nam Bodyholic Doubtless Hair & Body Mist', NULL, 19, NULL, 189000, NULL, NULL, NULL, NULL, NULL, 4, N'https://product.hstatic.net/1000006063/product/3_f3a49a927d9b4717a6bffe58f8569549_1024x1024.png', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'PB115               ', N'Nước Hoa Cao Cấp Hương Thơm Ngọt Ngào, Sang Trọng Marc Jacobs Daisy Eau So Intense Eau De Parfum', NULL, 19, NULL, 2339000, NULL, NULL, NULL, NULL, NULL, 4, N'https://product.hstatic.net/1000006063/product/marc_jacobs_2_866f323450024e33aa20e7fab0b73d65_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'PB116               ', N'Nước Hoa Dạng Xịt Lưu Hương Lâu Dài De Memoria', NULL, 19, NULL, 355000, NULL, NULL, NULL, NULL, NULL, 4, N'https://product.hstatic.net/1000006063/product/nuoc_hoa_4b037a4d169b4ce0b85da9f962fb2d7e_1024x1024__1__00f41b0dcecb4a8d879b57cb90f011d6_1024x1024.jpg', NULL, NULL)
INSERT [dbo].[tblProduct] ([ID], [codeProduct], [nameProduct], [descriptionProduct], [idSup], [quantityProductInput], [priceProductInput], [priceProductDown], [colorPro], [sizePro], [material], [genderUse], [IDStyle], [imageProduct1], [imageProduct2], [imageProduct3]) VALUES (4, N'PB117               ', N'Nước Hoa Nam Cao Cấp Hương Thơm Tươi Mát, Nam Tính Calvin Klein Eternity For Men Aqua EDT', NULL, 19, NULL, 1699000, NULL, NULL, NULL, NULL, NULL, 4, N'https://product.hstatic.net/1000006063/product/calvin_klein_eternity_for_men_aqua_edt_7398395820a645f5bc519149474cab01_1024x1024.jpg', NULL, NULL)
SET IDENTITY_INSERT [dbo].[tblProduct] OFF
GO
SET IDENTITY_INSERT [dbo].[tblStaff] ON 

INSERT [dbo].[tblStaff] ([IDStaff], [StaffName]) VALUES (1, N'Huyền')
INSERT [dbo].[tblStaff] ([IDStaff], [StaffName]) VALUES (2, N'Thư')
INSERT [dbo].[tblStaff] ([IDStaff], [StaffName]) VALUES (3, N'Vy')
SET IDENTITY_INSERT [dbo].[tblStaff] OFF
GO
SET IDENTITY_INSERT [dbo].[tblStyle] ON 

INSERT [dbo].[tblStyle] ([ID], [nameStyle]) VALUES (1, N'Chăm sóc cơ thể')
INSERT [dbo].[tblStyle] ([ID], [nameStyle]) VALUES (2, N'Chăm sóc tóc')
INSERT [dbo].[tblStyle] ([ID], [nameStyle]) VALUES (3, N'Trang điểm')
INSERT [dbo].[tblStyle] ([ID], [nameStyle]) VALUES (4, N'Nước hoa')
INSERT [dbo].[tblStyle] ([ID], [nameStyle]) VALUES (5, N'Chăm sóc da mặt')
SET IDENTITY_INSERT [dbo].[tblStyle] OFF
GO
SET IDENTITY_INSERT [dbo].[tblSupplierProduct] ON 

INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (1, N'Body essence')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (2, N'Body exfoliation')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (3, N'Deodorant')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (4, N'Dissolve')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (5, N'Hand skin care')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (6, N'Shower gel')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (7, N'Soap')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (8, N'Wax')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (9, N'Skin care process')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (10, N'Skin care set')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (11, N'Skin solution')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (12, N'Hair conditioner')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (13, N'Hair dye')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (14, N'Incubated cream hair')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (15, N'Shampoo')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (16, N'Eye makeup')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (17, N'Face makeup')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (18, N'Lip makeup')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (19, N'Bodymix')
INSERT [dbo].[tblSupplierProduct] ([idSup], [supplierName]) VALUES (20, N'Luxury perfume')
SET IDENTITY_INSERT [dbo].[tblSupplierProduct] OFF
GO
SET IDENTITY_INSERT [dbo].[tblUser] ON 

INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (1, N'lammyhuyen', N'Myhuyen2004xx@', N'admin')
INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (2, N'lammyhuyen', N'Myhuyen2004xx@', N'admin')
INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (1002, N'Huyenlam', N'Huyenne123', N'admin')
INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (2002, N'ahhahhahha', N'Myhuyen2004xx@', NULL)
INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (3002, N'Huyền', N'Myhuyen2004xx@', NULL)
INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (3003, N'anhthu', N'anhthu6023789',N'anhthu6023789')
INSERT [dbo].[tblUser] ([userID], [userName], [userPass], [userRole]) VALUES (3003, N'ahhahhahha', N'Myhuyen2004xx@', NULL)
SET IDENTITY_INSERT [dbo].[tblUser] OFF
GO
ALTER TABLE [dbo].[tblBill]  WITH CHECK ADD FOREIGN KEY([IDStaff])
REFERENCES [dbo].[tblStaff] ([IDStaff])
GO
ALTER TABLE [dbo].[tblBill]  WITH CHECK ADD  CONSTRAINT [fk_tblbill_code] FOREIGN KEY([codeCus])
REFERENCES [dbo].[tblCustumer] ([codeCus])
GO
ALTER TABLE [dbo].[tblBill] CHECK CONSTRAINT [fk_tblbill_code]
GO
ALTER TABLE [dbo].[tblDetailBill]  WITH CHECK ADD FOREIGN KEY([CodeProduct])
REFERENCES [dbo].[tblProduct] ([codeProduct])
GO
ALTER TABLE [dbo].[tblDetailBill]  WITH CHECK ADD FOREIGN KEY([IDBill])
REFERENCES [dbo].[tblBill] ([IDBill])
GO
ALTER TABLE [dbo].[tblProduct]  WITH CHECK ADD FOREIGN KEY([IDStyle])
REFERENCES [dbo].[tblStyle] ([ID])
GO
ALTER TABLE [dbo].[tblProduct]  WITH CHECK ADD FOREIGN KEY([idSup])
REFERENCES [dbo].[tblSupplierProduct] ([idSup])
GO
